### ISSUE TITLE
how to install and use..?

### ISSUE THREAD

**Issue by krauwu** [Zhuzili-lys/Underwater-Lidar-Simulation#1]

**Comment by Zhuzili-lys** [comment]
Hey Krauwu, thank you for your question. The code runs on MATLAB R2022b with dependency of Signal Processing toolbox. I will add it to readme. 

Besides, if you are interested in simulating the underwater Lidar in real use, the simulation may not be sufficient since its just implementation of a poorly-written paper. I regret implementing this paper immediatly after i realize that the model is poor.  :(

But if you are just using it for learning fastICA, just go ahead and have fun. :)
